/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RegistrationSuccessRouteImport } from './routes/registration-success'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminCoordinatorsRouteImport } from './routes/admin.coordinators'
import { Route as AdminDatesRouteImport } from './routes/admin.dates'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminExportsRouteImport } from './routes/admin.exports'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminRegistrationControlRouteImport } from './routes/admin.registration-control'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSuccessRoute = RegistrationSuccessRouteImport.update({
  id: '/registration-success',
  path: '/registration-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoordinatorsRoute = AdminCoordinatorsRouteImport.update({
  id: '/coordinators',
  path: '/coordinators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatesRoute = AdminDatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExportsRoute = AdminExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationControlRoute =
  AdminRegistrationControlRouteImport.update({
    id: '/registration-control',
    path: '/registration-control',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/coordinators': typeof AdminCoordinatorsRoute
  '/admin/dates': typeof AdminDatesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registration-control': typeof AdminRegistrationControlRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/coordinators': typeof AdminCoordinatorsRoute
  '/admin/dates': typeof AdminDatesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registration-control': typeof AdminRegistrationControlRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/registration-success': typeof RegistrationSuccessRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/coordinators': typeof AdminCoordinatorsRoute
  '/admin/dates': typeof AdminDatesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/exports': typeof AdminExportsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/registration-control': typeof AdminRegistrationControlRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/payment'
    | '/register'
    | '/registration-success'
    | '/admin/contact'
    | '/admin/coordinators'
    | '/admin/dates'
    | '/admin/events'
    | '/admin/exports'
    | '/admin/faq'
    | '/admin/participants'
    | '/admin/payments'
    | '/admin/registration-control'
    | '/admin/registrations'
    | '/admin/settings'
    | '/events/$slug'
    | '/admin/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/payment'
    | '/register'
    | '/registration-success'
    | '/admin/contact'
    | '/admin/coordinators'
    | '/admin/dates'
    | '/admin/events'
    | '/admin/exports'
    | '/admin/faq'
    | '/admin/participants'
    | '/admin/payments'
    | '/admin/registration-control'
    | '/admin/registrations'
    | '/admin/settings'
    | '/events/$slug'
    | '/admin'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/payment'
    | '/register'
    | '/registration-success'
    | '/admin/contact'
    | '/admin/coordinators'
    | '/admin/dates'
    | '/admin/events'
    | '/admin/exports'
    | '/admin/faq'
    | '/admin/participants'
    | '/admin/payments'
    | '/admin/registration-control'
    | '/admin/registrations'
    | '/admin/settings'
    | '/events/$slug'
    | '/admin/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PaymentRoute: typeof PaymentRoute
  RegisterRoute: typeof RegisterRoute
  RegistrationSuccessRoute: typeof RegistrationSuccessRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-success': {
      id: '/registration-success'
      path: '/registration-success'
      fullPath: '/registration-success'
      preLoaderRoute: typeof RegistrationSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coordinators': {
      id: '/admin/coordinators'
      path: '/coordinators'
      fullPath: '/admin/coordinators'
      preLoaderRoute: typeof AdminCoordinatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dates': {
      id: '/admin/dates'
      path: '/dates'
      fullPath: '/admin/dates'
      preLoaderRoute: typeof AdminDatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exports': {
      id: '/admin/exports'
      path: '/exports'
      fullPath: '/admin/exports'
      preLoaderRoute: typeof AdminExportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registration-control': {
      id: '/admin/registration-control'
      path: '/registration-control'
      fullPath: '/admin/registration-control'
      preLoaderRoute: typeof AdminRegistrationControlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminContactRoute: typeof AdminContactRoute
  AdminCoordinatorsRoute: typeof AdminCoordinatorsRoute
  AdminDatesRoute: typeof AdminDatesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminExportsRoute: typeof AdminExportsRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRegistrationControlRoute: typeof AdminRegistrationControlRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContactRoute: AdminContactRoute,
  AdminCoordinatorsRoute: AdminCoordinatorsRoute,
  AdminDatesRoute: AdminDatesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminExportsRoute: AdminExportsRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRegistrationControlRoute: AdminRegistrationControlRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PaymentRoute: PaymentRoute,
  RegisterRoute: RegisterRoute,
  RegistrationSuccessRoute: RegistrationSuccessRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
